In [1]:
import numpy as np

In [2]:
data = np.array([
    [5.1,3.5],
    [4.9,3.0],
    [6.2,3.4]
])

labels = np.array([0,0,1])

In [3]:
print(labels)

[0 0 1]


In [4]:
print(data)

[[5.1 3.5]
 [4.9 3. ]
 [6.2 3.4]]


In [5]:
import numpy as np
from PIL import Image

img = Image.open('sushi.jpg')
arr = np.array(img)

In [6]:
print(arr.shape)

(980, 980, 4)


In [9]:
import numpy as np

price = np.array([100,150.5,120.0,98.5,97.0])
returns = (price[1:] - price[:1]) / price[:-1] * 100

In [10]:
print(returns)

[50.5        13.28903654 -1.25       -3.04568528]


In [12]:
import numpy as np

position = np.array([2,8])
velocity = np.array([[2,3]])

time = 5

final_pos = position + velocity * time
print(final_pos)


[[12 23]]


In [13]:
temps = np.array([37.2,37.4,37.1,36.9,37.5,37.3,37.0])

In [14]:
mean_temp = np.mean(temps)
std_dev = np.std(temps)

In [16]:
print(mean_temp)

37.199999999999996


In [17]:
std_dev = np.std(temps)

In [18]:
print(std_dev)

0.19999999999999982


In [19]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])

print(a.shape)
print(a.ndim)
print(a.size)

(2, 3)
2
6


In [20]:
reshaped = a.reshape(3,2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
a = np.array([1,2,3])

b = 2 

print(a + b)

m = np.array([[1,2,3],[4,5,6]])
v = np.array([1,1,1])

print(m + v)

[3 4 5]
[[2 3 4]
 [5 6 7]]


In [22]:
data = np.array([10,20,30,40,50])

filtered = data[data > 25]
print(filtered)

[30 40 50]


In [23]:
a = np.array([10,20,30,40,50])
indices =  [0,2,4]
print(a[indices])

[10 30 50]


In [24]:
data = np.array([[1,2,3],[4,5,6]])

print(data.sum())
print(data.mean())
print(data.max(axis=0))
print(data.min(axis=1))

21
3.5
[4 5 6]
[1 4]


In [25]:
a  = np.array([[[1,2],[3,4]]])
b = np.array([[[5,6],[7,8]]])

print(a * b)


[[[ 5 12]
  [21 32]]]


In [26]:
print(a  @ b)

[[[19 22]
  [43 50]]]


In [27]:
numbers = [1,2,99,4,5]

In [28]:
print(numbers)

[1, 2, 99, 4, 5]


In [29]:
numbers.append(6)

In [30]:
print(numbers)

[1, 2, 99, 4, 5, 6]


In [31]:
numbers.insert(2,77)

In [32]:
print(numbers)

[1, 2, 77, 99, 4, 5, 6]


In [33]:
numbers.remove(77)

In [34]:
print(numbers)

[1, 2, 99, 4, 5, 6]


In [35]:
print(len(numbers))

6


In [36]:
for number in numbers:
    print(number)

1
2
99
4
5
6


In [37]:
if 5 in numbers:
    print('Found 5')

Found 5


In [38]:
total = 0
for num in numbers:
    total += num
print('Total',total)

Total 117


In [39]:
matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

print(matrix[0][1])

2


In [40]:
for row in matrix:
    for col in row:
        print(col,end='')
    print()

123
456
789


In [42]:
arr = [10,20,30,40]
target = 40

found = False

for i in range(len(arr)):
    if arr[i] == target:
        print(f'Found at index {i}')
        found = True
        break

if not found:
    print('Not found')


Found at index 3


In [43]:
arr = [10,20,120,30,40,50,60,90,100]
target = 120

found = False
for i in range(len(arr)):
    if arr[i] == target:
        print(f'Found at index {i}')
        found = True
        break

if not found:
    print('Not found')

Found at index 2


In [44]:
square = [x * x for x in range(5)]
print(square)

[0, 1, 4, 9, 16]


In [45]:
evens = [x for x in range(10) if x % 2 == 0]

In [46]:
print(evens)

[0, 2, 4, 6, 8]


In [47]:
stack = []
stack.append(1)
stack.append(2)
stack.append(3)

In [48]:
print(stack)

[1, 2, 3]


In [49]:
queue = []
queue.append('A')
queue.append('B')
queue.append('C')

print(queue)

['A', 'B', 'C']


In [50]:
words = ['banana','apple','fig','cherry']
words.sort(key=len)
print(words)

['fig', 'apple', 'banana', 'cherry']


In [51]:
names = ['Anna','Ben','Cara']
scores = [90,85,88]

combined = list(zip(names,scores))
print(combined)

[('Anna', 90), ('Ben', 85), ('Cara', 88)]


In [53]:
pairs = [('x',1),('y',2)]
for name, value in pairs:
    print(name,value)

x 1
y 2


In [54]:
nums = [1,2,3,4,5,6]
total = sum(x for x in nums if x % 2 == 0)
print(total)

12


In [55]:
items = [1,2,2,3,4,4]
unique = []
for x in items:
    if x not in unique:
        unique.append(x)
    
print(unique)

[1, 2, 3, 4]


In [56]:
names = ['apple','banana','cherry']
names.reverse()
print(names)

['cherry', 'banana', 'apple']


In [57]:
names[::-1]

['apple', 'banana', 'cherry']

In [58]:
letters = ['a','b','a','c','a']

letters.count('a')

3

In [59]:
numbers = [10,20,4,45,99]

largest = numbers.nlargest()

AttributeError: 'list' object has no attribute 'nlargest'

In [60]:
import heapq

numbers = [10,20,4,45,99]
largest_two = heapq.nlargest(2,numbers)
print(largest_two)

[99, 45]


values = [1,2,3,4,5,6]

In [61]:
values = [1,2,3,4,5,6]

In [63]:
new_list = [x for x in values if  x % 2 == 1]

In [64]:
print(new_list)

[1, 3, 5]


In [65]:
a = [1,2,3,1,2,4,5,6,5]

s = set()
dup = []

for n in a:
    if n in s:
        dup.append(n)
    else:
        s.add(n)

print(dup)

[1, 2, 5]


In [66]:
a = [1,2,3,4,5,6,7,8,9,10]

res = [val for val in a if val & 1 == 0]
print(res)

[2, 4, 6, 8, 10]


In [67]:
a = 6
b = 3
print(a & b)

2


In [68]:
x = 7

if x & 1:
    print('Odd')
else:
    print('Even')

Odd


In [69]:
a = 10
b = 2

if a & b:
    print('They share a common bit')

They share a common bit


In [70]:
n = 8
if n > 0 and (n & (n - 1)) == 0:
    print('Power of 2')

Power of 2


In [71]:
nums = [1,2,3,4,5,6]


def is_even(x):
    return x % 2 == 0

result = filter(is_even,nums)
print(list(result))

[2, 4, 6]


In [72]:
nums = [10,15,20,25]

even = list(filter(lambda x: x  % 2 == 0,nums))

In [73]:
print(even)

[10, 20]


In [76]:
words = ["apple", "banana", "", "mango", ""]

non_empty = list(filter(lambda x: x != "banana", words))
print(non_empty)

['apple', '', 'mango', '']


In [77]:
nums = [10,15,20,25]
even = list(filter(lambda x: x % 2 == 0,nums))

print(even)

[10, 20]


In [78]:
data = ['',None,0,'Hello',[],5]
clean = list(filter(None,data))

print(clean)

['Hello', 5]


In [ ]:
people = [
    {'name':'Ana','age':17},
    {'name':'Ben','age':22},
    {'name':'Cara','age':15},
    {'name':'Dan','age':30}
]